# Generated by Django 4.2 on 2024-03-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
    ]
